### PR TITLE
Reset functionality

### PR DESCRIPTION
**Pull request by stack461**

### CODE REVIEW

**Review by shantimorrell — DISMISSED** [review]
My understanding was Clotilde was hoping for an option that deleted just the input images/directories (instead of having to delete them one by one), not all of the calibration files, but I may have misinterpreted her feedback.

I'm approving this since it looks good, and we can always check in to see which would be most useful for users

**Comment by adulbrich** [comment]
Let's have two buttons, to build upon Shanti said:
- One "Reset All" that removes all inputs (file paths, directories, images, and manual inputs)
- One "Clear All Images" or "Clear All Directories" to remove only the images or directories (resp.)

**Comment by stack461** [comment]
I wanted to leave this comment. I changed it so only the images are deleted as Clotilde mentioned I also implemented the change between images and directories deletes the inputs and lastly, I figured out the directory type checking issue. A user was allowed to upload images and upon switching to directories the images remained so that was the type checking I was referring to but this resolved itself when the input is cleared when switching. Lastly, the clearing of the entire form is a bit involved due to the fact that I can not directly access the elements (document.getElementById).value = "" as I don't think Next enables you to do this.

**Review by shantimorrell — APPROVED** [review]
This looks great for deleting the input images/dirs and switching between images and batch processing!

As for being able to reset the typed inputs, their state is stored in viewSettings and the input fields have the value of the React state, so I believe using the following should work to reset them to their default values:

```
setViewSettings({
      diameter: "",
      xleft: "",
      ydown: "",
      vv: "",
      vh: "",
      targetRes: "1000",
})
```

**Pull request merged**
