### PR TITLE
Initialized Starlight docs

### LINKED ISSUE #23: Initialize Starlight docs
1. In the fork, create new branch, and create a new directory called `docs`
2. Initialize the documentation with Starlight by following tutorial here: https://starlight.astro.build/getting-started/
3. Run documentation site and make sure it works
4. Open PR

### PR DESCRIPTION
**Pull request by shantimorrell**
Initialized Starlight docs in ./src-docs

Can be merged after the Tauri app has been initialized

Closes #23

### CODE REVIEW

**Review by adulbrich — CHANGES_REQUESTED** [review]
put the contents of `/app` in root and don't remove examples

**Review by adulbrich — DISMISSED** [review]

**Comment by stack461** [comment]
Looks ready to push to main branch.

**Review by stack461 — DISMISSED** [review]
Looks ready to push to main branch.

**Review by adulbrich — COMMENTED** [review]
Is it normal that all example files are gone?

**Review by adulbrich — APPROVED** [review]
Excellent

**Pull request merged**
